<?php
class PostTableSeeder extends Seeder {
	public function run() {
		DB::table('posts')->delete();
		DB::unprepared('ALTER TABLE posts AUTO_INCREMENT=1'); 
		DB::table('posts')->insert(
		[
			[
				'username' => 'Alexandre',
				'password' => Hash::make('Alexandre'),
				'remember_token' => '',
				'role' => 'teacher',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Abel',
				'password' => Hash::make('Abel'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Al',
				'password' => Hash::make('Al'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Alan',
				'password' => Hash::make('Alan'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Arthur',
				'password' => Hash::make('Arthur'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Carl',
				'password' => Hash::make('Carl'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Blaise',
				'password' => Hash::make('Blaise'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Isaac',
				'password' => Hash::make('Isaac'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Steve',
				'password' => Hash::make('Steve'),
				'remember_token' => '',
				'role' => 'first_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Alfred',
				'password' => Hash::make('Alfred'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Brendan',
				'password' => Hash::make('Brendan'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'David',
				'password' => Hash::make('David'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'George',
				'password' => Hash::make('George'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Jim',
				'password' => Hash::make('Jim'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Leslie',
				'password' => Hash::make('Leslie'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Maria',
				'password' => Hash::make('Maria'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Rasmus',
				'password' => Hash::make('Rasmus'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username' => 'Tim',
				'password' => Hash::make('Tim'),
				'remember_token' => '',
				'role' => 'final_class',
				'created_at' => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at' => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			]
		]);
	}
} ?>