<?php
class UserTableSeeder extends Seeder {
	public function run() {
		DB::table('users')->delete();
		DB::unprepared('ALTER TABLE users AUTO_INCREMENT=1'); 
		DB::table('users')->insert(
		[
			[
				'username'       => 'Alexandre',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Alexandre'),
				'remember_token' => '',
				'role'           => 'teacher',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Abel',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Abel'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Al',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Al'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Alan',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Alan'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Arthur',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Arthur'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Carl',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Carl'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Blaise',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Blaise'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Isaac',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Isaac'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Steve',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Steve'),
				'remember_token' => '',
				'role'           => 'first_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Alfred',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Alfred'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Brendan',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Brendan'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'David',
				'email'          => 'email@email.com',
				'password'       => Hash::make('David'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'George',
				'email'          => 'email@email.com',
				'password'       => Hash::make('George'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Jim',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Jim'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Leslie',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Leslie'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Maria',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Maria'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Rasmus',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Rasmus'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			],
			[
				'username'       => 'Tim',
				'email'          => 'email@email.com',
				'password'       => Hash::make('Tim'),
				'remember_token' => '',
				'role'           => 'final_class',
				'created_at'     => \Carbon\Carbon::createFromDate(2014,02,03)->toDateTimeString(),
				'updated_at'     => \Carbon\Carbon::createFromDate(2014,03,03)->toDateTimeString(),
			]
		]);
	}
} ?>